config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout" }
  resources :users

  root "posts#index"

  resources :posts do
    resources :comments
  end

  get "pages/index"
  get "pages/about"
  get "pages/contact"
  post "pages/thank_you"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, User, id: user.id
      can :manage, Comment, id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :name, :body, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments

  mount_uploader :picture, PictureUploader
  serialize :picture, JSON # use for SQLite

  validates :title, :content, :category_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: "Your comment has been saved successfully." }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { redirect_to @post, alert: "Your comment was not saved." }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post, alert: "Your comment was deleted." }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :name, :body)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def about; end

  def contact; end

  def thank_you
    @name = params[:name]
    @subject = params[:subject]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @subject, @message).deliver_now
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]

  def index
    if params[:category].blank?
      @posts = Post.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
    @comments = @post.comments.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def edit
    @post.user_id = current_user.id
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :category_id, :title, :intro, :content, :picture)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/comments/_comment.html.erb
<div>
  <p><strong><%= comment.name %></strong><br>
    <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small><br>
    <%= simple_format(comment.body) %><br />
    <% if can? :destroy, comment %>
    <%= link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <hr>
  </p>
</div>

app/views/comments/_form.html.erb
<% if signed_in? %>
  <h2>Add a comment:</h2>
  <%= form_for([@post, @post.comments.build], remote: true) do |f| %>
    <div class="field">
      <%= f.label :name, "Name:" %>
      <%= f.text_field :name, size: 30, class: "input", placeholder: "Your Name", require: true %>
    </div>
    <div class="field">
      <%= f.label :body, "Comment:" %>
      <%= f.text_area :body, cols: 30, rows: 10, class:"input", placeholder: "Your Comment", require: true %>
    </div>
    <div class="actions">
      <%= f.submit(class: "btn btn-dark") %>
    </div>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$('#new_comment').html("Thank you for your comment!");

$('.post-comments').prepend("<%= j render @comment %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Blog:Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Fontstacks -->
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Spinnaker" />
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quattrocento+Sans" />
        <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Architects+Daughter" />
  </head>

  <body>

    <%= render 'shared/nav' %>

    <% if notice %>
        <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>

    <%= render 'shared/jumbotron' %>


    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="container">
  <h3>Welcome to <b>THE BLOG:PROJECT</b> </h3><br>
  <p>This project is designed to create an open community
    of bloggers and writers and curious people. If you always wanted to start writing
    or posting or blogging or sharing, then this is the right place for you.
    Feel free to sign up and become a writer.
    We started to blog about our experiences and love to share our encounters with you,
    and him and her and whoever crosses our way.
    While people are tend to be easy on complaining we want to be grateful instead
    and share the stories that let us be grateful and discover how wonderful life
    can be and how you can always see the beauty in the detail when you try.
  </p><br><br>

  <h3>Storytelling</h3><br>
  <p>We strongly believe that reading or hearing a good story has the same effect as
    eating chocolate: it makes you happy. Being more positive while filling your mind
    with good thoughts lets you see how precious your time is and how wonderful
    things can happen to you when you're open for these daily little wonders. It doesn't
    have to be a huge mindblowing incident, sometimes it's just a smile when wishing
    someone a good rest of the day.<br>
    Share your story with other people and create something new. A new movement,
    a group of positive thinkers. Feed your soul with some good stories that
    warm up your heart.
  </p><br><br>

  <h3><b>THE BLOG:PROJECT</b> Founder</h3><br>
  <p>Hi, I am Franzi: Web Developer. I created this project for many reasons. First,
    I wanted to share some of my stories that I've been carrying around and felt these
    are worth a sharing.<br>
    Second, as web developer I wanted to build a web app that has an appealing
    layout and well-working functionalities. While being the creator, this can just
    be the start and will always be evolving and grow and change. Change is a good thing.<br>
    Third, I was getting bored of facebook. Although I am a huge fan of being connected
    to my friends and aquaintances, I just couldn't stand another post of <q><em>someone
    is interested in an event</em></q> or reading posts of people complaining
    or even worse insulting others via comments.<br>
    I just love reading but instead of wasting time on facebook, I much rather dedicate
    my time to reading inspiring books or stories, so I thought
    I might as well just create such a format of social community in the sense of
    <em><b>Social Storytelling</b></em><br>
    Fourth, I didn't just want to create a blog that I am the only powerful owner of,
    I love creating and producing but not possessing, therefore I decided to go for
    this format of contributing and be inspired myself while reading other
    writer's stories. And as four is always a good number, I am gonna leave you with
    these.<br>
    If you have any further questions, feel free to reach out to me via the contact page.<br>
    If you're eager to post an article here, go ahead an sign up and become part of
    <b>The BLOG:PROJECT</b>.
  </p>




</section>

app/views/pages/contact.html.erb
<section class="container">
  <h1>Contact me</h1>
  <%= flash[:notice] %>
  <%= form_with(url:"/pages/thank_you", method: "post", local: true) do |form| %>
  <div calss="row">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, size: 30, class: "input form-control", placeholder: "Please enter your name", required: true %>
    </div>
    <div class="form-group">
      <%= form.label :subject %>
      <%= form.text_field :subject,  size: 30, class: "input form-control", placeholder: "Add a subject" %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email,  size: 30, class: "input form-control", placeholder: "Please enter your Email-address here", required: true %>
    </div>
    <div class="form-group">
      <%= form.label :message %>
      <%= form.text_area :message,  cols: 30, rows: 8, class: "input form-control", rows: 5, placeholder: "Write your message here", required: true %>
    </div>
    <div class="actions">
      <%= form.submit "Send", class: "btn btn-dark" %>
    </div>
    <% end %>
  </div><!-- /row -->

</section>

app/views/pages/index.html.erb
<section class="container">
  <h1>Home</h1>
  <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
  </p>

  <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
   tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
   vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
   no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
   consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
   et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo      dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
   ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
   Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
   Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
   Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer
  </p>


</section>

app/views/pages/thank_you.html.erb
<section class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <p>Thank you for your message. We will reach out to you soon.</p>
    </div>
  </div>
</section>

app/views/posts/_comments.html.erb
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :image, "If you'd like to add an Image: (optional)" %>
      <%= form.text_field :image, size: 30, class: "input form-control", placeholder: "Paste an image link" %>
    </div>

    <div class="field">
      <%= form.label "If you'd like to upload a picture: (optional)" %>
      <%= form.file_field :picture %>
    </div>

    <div class="field">
      <%= form.label :category_id, "Select a category:" %>
      <%= form.collection_select(:category_id, Category.all, :id, :name, {prompt: "Please select..."}) %>
    </div>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, size: 30, class: "input form-control", placeholder: "Your title" %>
    </div>

    <div class="field">
      <%= form.label :intro %>
      <%= form.text_area :intro, cols: 30, rows: 5, class: "input form-control", placeholder: "Your introduction" %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, cols: 30, rows: 15, class: "input form-control", placeholder: "Write your story here..." %>
    </div>

    <div class="actions">
      <%= form.submit(class: "btn btn-dark") %>
    </div>
  <% end %>

</div>

app/views/posts/_new_comment.html.erb
<div>
  <% if signed_in? %>
    <h2>Add a comment:</h2>
    <%= form_for([@post, @post.comments.build], remote: true) do |f| %>
      <div class="field">
        <%= f.label :name, "Your name: (required)" %>
        <%= f.text_field :name, size: 30, class: "input form-control", placeholder: "Your Name", require: true %>
      </div>
      <div class="field">
        <%= f.label :body, "Your comment: (required)" %>
        <%= f.text_area :body, cols: 30, rows: 10, class:"input form-control", placeholder: "Your Comment", require: true %>
      </div>
      <div class="actions">
        <%= f.submit(class: "btn btn-dark") %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<section class="container">
  <h1>Editing Post</h1>

  <%= render 'form', post: @post %><br><br>

  <%= link_to 'Show', @post %> | <%= link_to 'Back', posts_path %>

</section>

app/views/posts/index.html.erb
<section class="container">
  <div class="posts">
    <% @posts.each do |post| %>
      <p class="date">
        <em><%= (post.created_at).strftime("%B %e, %Y") %></em>
      </p>
      <h2><%= post.title %></h2>
      <p><%= post.intro unless nil? %></p>
      <p><%= post.content.truncate(300) %></p>
      <p><%= link_to 'Read more', post %><% if can? :update, post %> | <%= link_to 'Edit', edit_post_path(post) %> | <% end %><% if can? :destroy, post %> <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></p>
      <hr>
    <% end %>
  </div> <!-- /container-posts-->
  <br>
  <div class="btn btn-light">
    <% if signed_in? %>
      <%= link_to 'New Post', new_post_path %>
    <% end %>
  </div>
<br><br>
</section>

app/views/posts/new.html.erb
<section class="container">
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>
</section>

app/views/posts/show.html.erb
<section class="container">

  <p>
    <% if @post.image? %>
      <%= image_tag(@post.image, class: "img-fluid") %>
    <% end %>
  </p>
  <p class="img-fluid">
    <% if @post.picture? %>
      <%= image_tag(@post.picture_url(:default).to_s, class: "img-fluid") %>
    <% end %>
  </p>
  <p class="date">
    <em><%= (@post.created_at).strftime("%B %e, %Y") %></em>
  </p>
  <h2><%= @post.title %></h2>
  <p>
    <%= @post.intro %>
  </p>
  <p>
    <%= simple_format(@post.content) %><br><br>
  </p>

  <br />
  <h2><%= @post.comments.count %> Comments </h2>
  <%= render 'new_comment' %>

  <div class="post-comments">
    <%= render 'comments' %>
  </div>

  <% if (signed_in? && ((current_user.id == @post.user_id) || current_user.admin?)) %>
  <%= link_to 'Edit', edit_post_path(@post) %> | <% end %> <%= link_to 'Back', posts_path %><br><br>
</section>

app/views/shared/_footer.html.erb
<footer class="site-footer container-fluid">
  <p>&copy 2019 THE BLOG:PROJECT</p>
</footer>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid">
  <div>
    <h1>THE BLOG:PROJECT</h1>
    <nav>
      <ul class="nav justify-content-center">
          <% Category.all.each do |category| %>
            <li class="nav-item">
              <b><%= link_to category.name, posts_path(category: category.name) %></b>
            </li>
          <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <a class="navbar-brand" href="/posts#index"><b>THE BLOG:PROJECT</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
   data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
   aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path %> <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to "About", pages_about_path %>
      </li>
      <li class="nav-item">
      <%= link_to "Contact", pages_contact_path %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to('Login', new_user_session_path, class: "nav-link") %>
      </li>
      <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<section class="container">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name, size: 30, class: "input" %>
    </div>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, size: 30, class: "input" %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, size: 30, class: "input" %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email, size: 30, class: "input" %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br>
      <% end %>
      <%= form.password_field :password, autocomplete: "new-password", class: "input", size: 30 %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, autocomplete: "new-password", class: "input", size: 30 %>
    </div>

    <div class="actions">
      <%= form.submit(class: "btn btn-dark") %>
    </div>
  <% end %>
</section>

app/views/users/edit.html.erb
<section class="container">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</section>

app/views/users/index.html.erb
<section class="container">
  <h1>Users</h1>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.user_name %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <p><%= link_to new_user_path, class: "btn btn-dark" do %>
    New User
  <% end %><br></p>

</section>

app/views/users/new.html.erb
<section class="container">

  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %>

</section>

app/views/users/show.html.erb
<section class="container">

  <p>
    <strong>Username:</strong>
    <%= @user.user_name %>
  </p>

  <p>
    <strong>First Name:</strong>
    <%= @user.first_name %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= @user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</section>